services:
  realsense_ros2:
    extends:
      file: docker/docker-compose-nvidia.yml
      service: realsense_ros2
    container_name: sgd_realsense
    networks:
      - ros_bridge
networks:
  ros_bridge:
    external: true
